import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maghfira & Firyal
 */
public class FormRegister extends javax.swing.JFrame {

    /**
     * Creates new form FormRegister
     */
    
     HashTable HS;
    Antrian antrian;
    public int i = 1;
    Queue kamar;
    
    public FormRegister() {
        initComponents();
        antrian = new Antrian();
        HS = new HashTable(20);
        kamar = new Queue(31);
    }
    
    public void Reset(){
        id_pasien.setText(null);
        nama.setText(null);
        asal.setText(null);
        nokamar.setText(null);
    }  
    
    public void Reset1(){
        search.setText(null);
    }
    
    
    int noKamar = 0;
    int jmlhkmr=30;
    
    public void Kamar(){
        noKmr.setText("0");
        jmlhkamar.setText("0");
    }
    
    public void tambahkamar(){
        noKamar++;
        String kmr = "Pasien "+noKamar;
        kamar.add(kmr);
        String cvt = String.valueOf(kamar.size());
        noKmr.setText(cvt);
        jmlhkamar.setText(""+(jmlhkmr-noKamar));
    }
    
    public void kurangikamar(){
        noKamar--;
        String kmr = "Pasien "+noKamar;
        kamar.remove();
        String cvt = String.valueOf(kamar.size());
        noKmr.setText(cvt);
        jmlhkamar.setText( String.valueOf(30 - noKamar));
    }
    
   public void doctor(){
        int Data = Integer.parseInt(nokamar.getText());
        
        
        HS.insert(Data, nama.getText(), nmDokter.getSelectedItem().toString());
        HS.displayTable();

        DefaultTableModel dataModel = (DefaultTableModel) listDokter.getModel();

         if(HS.hashArray[Data] == null){ 
         HS.hashArray[Data] = null;
         
            }          
            else if(dataModel.getValueAt(Data - 1, 0).toString() != "KOSONG"&& dataModel.getValueAt(Data - 1, 1).toString() != "KOSONG"&& dataModel.getValueAt(Data - 1, 2).toString() != "KOSONG"){     
            
            while (dataModel.getValueAt(Data - 1, 0).toString() != "KOSONG"&& dataModel.getValueAt(Data - 1, 1).toString() != "KOSONG"&& dataModel.getValueAt(Data - 1, 2).toString() != "KOSONG") {
            ++Data; 
            Data %= HS.size;         
           }
             
            
            dataModel.setValueAt(HS.hashArray[Data].getNmPasien(), Data-1, 1);
            dataModel.setValueAt(HS.hashArray[Data].getNmDokter(), Data-1, 2);
            
            }else{
                
                dataModel.setValueAt(HS.hashArray[Data].getNmPasien(), Data-1, 1);
                dataModel.setValueAt(HS.hashArray[Data].getNmDokter(), Data-1, 2);
            }    
         
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jmlhkamar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        noKmr = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nokamar = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        clear1 = new javax.swing.JButton();
        show = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        health = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listDokter = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        areadata = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nmDokter = new javax.swing.JComboBox<>();
        penyakit = new javax.swing.JComboBox<>();
        asal = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        id_pasien = new javax.swing.JTextField();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 750, 210, 30));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setText("Kamar");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setText("Cari Kamar :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 750, -1, -1));

        jmlhkamar.setBackground(new java.awt.Color(255, 255, 255));
        jmlhkamar.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jmlhkamar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlhkamar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204)));
        getContentPane().add(jmlhkamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 140, 100));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setText("Sisa Kamar :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setText("Kamar Terisi :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        noKmr.setBackground(new java.awt.Color(255, 255, 255));
        noKmr.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        noKmr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noKmr.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204)));
        getContentPane().add(noKmr, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 140, 100));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setText("Nama Dokter ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setText("Data Pasien dan Dokter :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setText("Data Pasien :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        nokamar.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        getContentPane().add(nokamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 420, 30));

        Search.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Search.setText("SEARCH");
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
        });
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 750, 110, 30));

        clear1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        clear1.setText("RESET");
        clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear1ActionPerformed(evt);
            }
        });
        getContentPane().add(clear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 260, 110, 40));

        show.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        show.setText("SHOW");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        getContentPane().add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 210, 110, 40));

        logout.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 30, 110, 40));

        health.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        health.setText("HEALTHY");
        health.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healthActionPerformed(evt);
            }
        });
        getContentPane().add(health, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 160, 110, 40));

        add.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 110, 110, 40));

        listDokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "KOSONG", "KOSONG"},
                {"2", "KOSONG", "KOSONG"},
                {"3", "KOSONG", "KOSONG"},
                {"4", "KOSONG", "KOSONG"},
                {"5", "KOSONG", "KOSONG"},
                {"6", "KOSONG", "KOSONG"},
                {"7", "KOSONG", "KOSONG"},
                {"8", "KOSONG", "KOSONG"},
                {"9", "KOSONG", "KOSONG"},
                {"10", "KOSONG", "KOSONG"},
                {"11", "KOSONG", "KOSONG"},
                {null, null, null}
            },
            new String [] {
                "No", "Nama Pasien", "Nama Dokter"
            }
        ));
        jScrollPane4.setViewportView(listDokter);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 420, 430, 320));

        tabel.setColumns(20);
        tabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tabel.setRows(5);
        jScrollPane2.setViewportView(tabel);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 550, 360));

        areadata.setColumns(20);
        areadata.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        areadata.setRows(5);
        jScrollPane1.setViewportView(areadata);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 310, 360));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setText("Data Pasien Lengkap :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setText("Penyakit");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Nama");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Id_Pasien");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Rumah Sakit Jiwa Winford");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 470, 40));

        nmDokter.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        nmDokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr. Budi", "Dr. Tsaamy", "Dr. Andi", "Dr. Zalfa", "Dr. Sentosa" }));
        nmDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmDokterActionPerformed(evt);
            }
        });
        getContentPane().add(nmDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 420, 30));

        penyakit.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        penyakit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Skizofrenia", "Gangguan Bipolar", "Depresi", "Anxiety", "Gamgguan Kepribadian", "Gangguan Psikotis", "Gangguan Obsesif Kompulsif (OCD)", "Gangguan Stres Pascatrauma (PTSD)", "Eating Disorder" }));
        penyakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penyakitActionPerformed(evt);
            }
        });
        getContentPane().add(penyakit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 420, 30));

        asal.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        getContentPane().add(asal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 420, 30));

        nama.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 420, 30));

        id_pasien.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        id_pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_pasienActionPerformed(evt);
            }
        });
        getContentPane().add(id_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 420, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\File Praktikum Kuliah\\Sems 3\\PrakBasdat\\RumahSakitJiwa\\Matthew Thiebes.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 820));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

       int idPasien = Integer.parseInt(id_pasien.getText());
       String namaPasien = nama.getText();
       String asalPasien = asal.getText();
       String penyakitPasien = penyakit.getSelectedItem().toString();
       antrian.enqueue(idPasien, namaPasien, asalPasien, penyakitPasien);
       areadata.setText(areadata.getText()+ "Id_Pasien  : "+id_pasien.getText()+"\n\tNama :"+nama.getText()+"\n\tAsal :"+asal.getText()+"\n\tPenyakit :"+penyakit.getSelectedItem().toString()+"\n");
       tambahkamar();
       doctor();
       Reset();
    }//GEN-LAST:event_addActionPerformed

    private void healthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healthActionPerformed
        String isiDequeue =  antrian.dequeue();
        areadata.setText(isiDequeue);
        kurangikamar();
    }//GEN-LAST:event_healthActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int dialogbtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this,"Apakah Administrasi Sudah Selesai?", "Peringatan", dialogbtn);
          
        if (dialogResult == 0){
            Login log = new Login();
            log.setVisible(true);
            dispose();
            //jika keluar
        } else {
            //jika tidak keluar
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void id_pasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_pasienActionPerformed
       
    }//GEN-LAST:event_id_pasienActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        tabel.setText("");
        tabel.setText(antrian.view());
    }//GEN-LAST:event_showActionPerformed

    private void clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear1ActionPerformed
        Reset1();
    }//GEN-LAST:event_clear1ActionPerformed

    private void penyakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penyakitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penyakitActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased

    }//GEN-LAST:event_searchKeyReleased

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked
//  
       int Kmr = Integer.parseInt(search.getText());
       if (HS.find(Kmr) == null) {
            HS.hashArray[i] = null;
            JOptionPane.showMessageDialog(null, "Kamar : "+Kmr+" Dokternya tidak ditemukan");
        }else{
        JOptionPane.showMessageDialog(null, "Kamar : "+Kmr+" dengan dokter : "+ HS.getnmDokter(Kmr)+"\nditemukan");
        
       }
    }//GEN-LAST:event_SearchMouseClicked

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
//       
    }//GEN-LAST:event_SearchActionPerformed

    private void nmDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmDokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmDokterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Search;
    private javax.swing.JButton add;
    private javax.swing.JTextArea areadata;
    private javax.swing.JTextField asal;
    private javax.swing.JButton clear1;
    private javax.swing.JButton health;
    private javax.swing.JTextField id_pasien;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel jmlhkamar;
    private javax.swing.JTable listDokter;
    private javax.swing.JButton logout;
    private javax.swing.JTextField nama;
    private javax.swing.JComboBox<String> nmDokter;
    private javax.swing.JLabel noKmr;
    private javax.swing.JTextField nokamar;
    private javax.swing.JComboBox<String> penyakit;
    private javax.swing.JTextField search;
    private javax.swing.JButton show;
    private javax.swing.JTextArea tabel;
    // End of variables declaration//GEN-END:variables
}
